# Generated by Django 3.1.1 on 2020-09-03 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_auto_20200903_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),  # noqa
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),  # noqa
        ),
    ]
