# Generated by Django 3.1.1 on 2020-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200903_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockorder',
            name='status',
        ),
        migrations.AddField(
            model_name='stock',
            name='units_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='order_type',
            field=models.CharField(default='buy', max_length=15),
        ),
    ]
